/* pmml_runtime.h — C ABI for pmmlruntime (ORT-style versioned Api table)
 *
 * This is the C package (like onnxruntime/include/onnxruntime/core/session/onnxruntime_c_api.h).
 * All language bindings (java/python/javascript) call through PmmlGetApi().
 * Do not edit by hand — generated by cbindgen from crates/pmmlruntime/src/ffi,
 * then hand-audited for include guard + version. See cbindgen.toml.
 *
 * PMML 4.4 without the JVM — 68us cold, 402ns/row, 16.5M rows/s batched.
 */

#ifndef PMML_RUNTIME_H
#define PMML_RUNTIME_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define PMML_API_VERSION 1u
#define PMML_VERSION_STRING "0.1.0" /* sync with Cargo.toml workspace.package.version + VERSION_NUMBER */

/* Opaque handles — never dereference in C. Owned by Rust (Arc/Box). */
typedef struct PmmlEnv PmmlEnv;
typedef struct PmmlSession PmmlSession;
typedef struct PmmlSessionOptions PmmlSessionOptions;
typedef struct PmmlRunOptions PmmlRunOptions;
typedef struct PmmlIoBinding PmmlIoBinding;
typedef struct PmmlStatus PmmlStatus; /* OrtStatus analogue — code + message */

/* Arrow C Data Interface forward decls (arrow/c/abi.h) — for zero-copy batch. */
struct ArrowArray;
struct ArrowSchema;

/* ---------- Enums ---------- */

typedef enum PmmlGraphOptimizationLevel {
    PMML_GRAPH_DISABLE_ALL   = 0,
    PMML_GRAPH_ENABLE_BASIC  = 1, /* default */
    PMML_GRAPH_ENABLE_EXTENDED = 2,
    PMML_GRAPH_ENABLE_ALL    = 3,
} PmmlGraphOptimizationLevel;

typedef enum PmmlLogLevel {
    PMML_LOG_VERBOSE = 0,
    PMML_LOG_INFO    = 1,
    PMML_LOG_WARNING = 2,
    PMML_LOG_ERROR   = 3,
    PMML_LOG_FATAL   = 4,
} PmmlLogLevel;

typedef enum PmmlErrorCode {
    PMML_OK                         = 0,
    PMML_ERR_INVALID_ARGUMENT       = 1,
    PMML_ERR_IO                     = 2,
    PMML_ERR_PARSE                  = 3,
    PMML_ERR_UNSUPPORTED_MARKUP     = 4,
    PMML_ERR_INVALID_VALUE          = 5,
    PMML_ERR_VALIDATION             = 6,
    PMML_ERR_OOM                    = 7,
    PMML_ERR_UNKNOWN                = 8,
} PmmlErrorCode;

/* Value — mirrors pmmlruntime::base::Value */
typedef enum PmmlValueTag {
    PMML_VALUE_MISSING    = 0,
    PMML_VALUE_CONTINUOUS = 1, /* double */
    PMML_VALUE_DISCRETE   = 2, /* SymbolId -> string via GetSymbolString */
} PmmlValueTag;

typedef struct PmmlValue {
    PmmlValueTag tag;
    union {
        double continuous;
        uint32_t discrete; /* SymbolId.0 — resolve via SessionGetSymbolString if needed */
    };
} PmmlValue;

/* ---------- Status (OrtStatus pattern) ---------- */

/* Caller must ReleaseStatus after checking. NULL means OK (like OrtStatus*). */
PmmlErrorCode PmmlGetErrorCode(const PmmlStatus* status);
const char*   PmmlGetErrorMessage(const PmmlStatus* status);
void          PmmlReleaseStatus(PmmlStatus* status);

/* ---------- Versioned Api table (ORT OrtApi pattern) ---------- */

typedef struct PmmlApi {
    uint32_t version; /* == PMML_API_VERSION for this struct layout */

    /* Env — owns global threadpool + logger. Shared across Sessions (Arc). */
    PmmlStatus* (*CreateEnv)(PmmlLogLevel log_level, const char* log_id, PmmlEnv** out);
    void        (*ReleaseEnv)(PmmlEnv* env);

    /* SessionOptions — builder before CreateSession (like OrtSessionOptions). */
    PmmlStatus* (*CreateSessionOptions)(PmmlSessionOptions** out);
    void        (*ReleaseSessionOptions)(PmmlSessionOptions* opts);
    PmmlStatus* (*SetGraphOptimizationLevel)(PmmlSessionOptions* opts, PmmlGraphOptimizationLevel level);
    PmmlStatus* (*SetIntraOpNumThreads)(PmmlSessionOptions* opts, int threads);
    PmmlStatus* (*SetInterOpNumThreads)(PmmlSessionOptions* opts, int threads);
    PmmlStatus* (*SetLogLevel)(PmmlSessionOptions* opts, PmmlLogLevel level);
    PmmlStatus* (*AddSessionConfigEntry)(PmmlSessionOptions* opts, const char* key, const char* value);
    PmmlStatus* (*AppendExecutionProvider)(PmmlSessionOptions* opts, const char* provider_name,
                                          const char* const* keys, const char* const* values, size_t count);
    /* provider_name: "CPU" (only provider today). Future: "WASM", "SIMD". Reserved for plugin EPs. */

    /* Session — from file or bytes (like OrtCreateSession / OrtCreateSessionFromArray). */
    PmmlStatus* (*CreateSession)(const PmmlEnv* env, const char* path,
                                 const PmmlSessionOptions* opts, PmmlSession** out);
    PmmlStatus* (*CreateSessionFromArray)(const PmmlEnv* env,
                                          const void* bytes, size_t len,
                                          const PmmlSessionOptions* opts, PmmlSession** out);
    void        (*ReleaseSession)(PmmlSession* sess);

    /* Metadata — like OrtSessionGetInputCount/Name/TypeInfo */
    PmmlStatus* (*SessionGetInputCount)(const PmmlSession* sess, size_t* out);
    PmmlStatus* (*SessionGetInputName)(const PmmlSession* sess, size_t index, const char** out); /* owned by Session, do not free */
    PmmlStatus* (*SessionGetOutputCount)(const PmmlSession* sess, size_t* out);
    PmmlStatus* (*SessionGetOutputName)(const PmmlSession* sess, size_t index, const char** out);
    PmmlStatus* (*SessionGetModelType)(const PmmlSession* sess, const char** out); /* "TreeModel", "MiningModel", ... */
    const char* (*GetVersionString)(void); /* PMML_VERSION_STRING */

    /* Field/Symbol introspection — mirrors Session::field_id / symbol_id */
    PmmlStatus* (*SessionGetFieldId)(const PmmlSession* sess, const char* name, uint32_t* out, int* found);
    PmmlStatus* (*SessionGetSymbolId)(const PmmlSession* sess, const char* s, uint32_t* out, int* found);

    /* Run — unified Batch (ORT InferenceSession::Run analogue). Single row = 1-element batch. */
    /* For now: inputs as (names[], values[], n). Outputs as pre-allocated values[] + count in/out. */
    PmmlStatus* (*Run)(PmmlSession* sess, const PmmlRunOptions* run_opts,
                       const char* const* input_names, const PmmlValue* input_values, size_t input_count,
                       const char* const* output_names, size_t output_count,
                       PmmlValue* output_values);

    /* Batch — RowMajor (flat) and Arrow columnar (zero-copy). Like ORT IoBinding but simpler for tabular. */
    PmmlStatus* (*RunBatch)(PmmlSession* sess, const PmmlRunOptions* run_opts,
                            const char* const* input_names, const PmmlValue* flat_values, size_t n_rows, size_t n_cols,
                            /* out */ PmmlValue* out_flat, size_t* out_rows_inout);

    /* Arrow — zero-copy (Arrow C Data Interface). Caller owns input ArrowArray/Schema; callee fills output. */
    PmmlStatus* (*RunArrow)(PmmlSession* sess, const PmmlRunOptions* run_opts,
                            const struct ArrowArray* input_array, const struct ArrowSchema* input_schema,
                            struct ArrowArray* out_array, struct ArrowSchema* out_schema);

    /* IoBinding — cache BatchCtx + buffers across runs (ORT IoBinding analogue for repeated scoring). */
    PmmlStatus* (*CreateIoBinding)(PmmlSession* sess, PmmlIoBinding** out);
    void        (*ReleaseIoBinding)(PmmlIoBinding* binding);
    PmmlStatus* (*BindInput)(PmmlIoBinding* binding, const char* name, PmmlValue value);
    PmmlStatus* (*BindInputArrow)(PmmlIoBinding* binding, const char* name,
                                  const struct ArrowArray* array, const struct ArrowSchema* schema);
    PmmlStatus* (*BindOutput)(PmmlIoBinding* binding, const char* name);
    PmmlStatus* (*RunWithBinding)(PmmlSession* sess, const PmmlRunOptions* run_opts, PmmlIoBinding* binding);
    PmmlStatus* (*CopyBindingOutputsToCpu)(PmmlIoBinding* binding, PmmlValue* out_flat, size_t* out_count);

    /* RunOptions per invocation (ORT RunOptions analogue) */
    PmmlStatus* (*CreateRunOptions)(PmmlRunOptions** out);
    void        (*ReleaseRunOptions)(PmmlRunOptions* opts);
    PmmlStatus* (*SetRunTag)(PmmlRunOptions* opts, const char* tag);
    PmmlStatus* (*SetRunLogLevel)(PmmlRunOptions* opts, PmmlLogLevel level);

} PmmlApi;

/* Get the Api table — like OrtGetApiBase()->GetApi(version). Returns NULL if version unsupported. */
const PmmlApi* PmmlGetApi(uint32_t version);

/* ---------- Deprecated shims (PmmlCreateEnv etc.) — kept for 0.1 compat, call PmmlGetApi internally ---------- */
int PmmlCreateEnv(PmmlEnv** out); /* returns PMML_OK int — prefer PmmlGetApi()->CreateEnv */
void PmmlReleaseEnv(PmmlEnv* env);
int PmmlCreateSession(PmmlEnv* env, const char* path, PmmlSession** out);
void PmmlReleaseSession(PmmlSession* sess);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* PMML_RUNTIME_H */
